services:
  webos-cli:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - home:/home/webos/
      - ./data:/home/webos/data:ro

volumes:
  home: