services:
  webos-cli:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - webos-vol:/home/webos/.webos
      - ssh:/home/webos/.ssh
      - ./data:/home/webos/data
volumes:
  webos-vol:
  ssh: